/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastro_e_Login;

import Cadastro_e_Login.TelaUsuarioLoginCL;
import Cadastro_e_Login.UsuarioBancoCL;

/**
 *
 * @author profslpa
 */
public class TelaModeradorBuscarCL extends javax.swing.JFrame {
    
    TelaModeradorMenuCL volta;
    UsuarioBancoCL banco;
    int ID;

    public void setID(int ID) {
        this.ID = ID;
    }
    
    
    public TelaModeradorBuscarCL() {
        initComponents();
        
    }
    
    
    public void mostrarPerfil() {
        lbl_id.setText("ID: " + ID);
        lbl_saldo.setText(String.valueOf("Saldo: " + banco.bancoDados[ID - 1].getSaldo()));
        lbl_nome.setText("Nome: " + banco.bancoDados[ID - 1].getNome());
        lbl_cpf.setText("CPF: " + banco.bancoDados[ID - 1].getCpf());
        lbl_email.setText("E-mail: " + banco.bancoDados[ID - 1].getEmail());
        lbl_telefone.setText("Telefone: " + banco.bancoDados[ID - 1].getTelefone());
        lbl_nomeDeUsuario.setText("Nome de usuário: " + banco.bancoDados[ID - 1].getNomeDeUsuario());
        lbl_senha.setText("Senha: " + banco.bancoDados[ID -1].getSenha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_saldo = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        lbl_nomeDeUsuario = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setForeground(new java.awt.Color(0, 0, 0));
        lbl_id.setText("ID: ");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_saldo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_saldo.setText("saldo aqui");
        jPanel1.add(lbl_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, 20));

        lbl_nome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nome.setText("informações aqui");
        jPanel1.add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 280, 20));

        lbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cpf.setText("informações aqui");
        jPanel1.add(lbl_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 280, 20));

        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("informações aqui");
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, 20));

        lbl_telefone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_telefone.setText("informações aqui");
        jPanel1.add(lbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 280, 20));

        lbl_nomeDeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nomeDeUsuario.setText("informações aqui");
        jPanel1.add(lbl_nomeDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 238, 20));

        lbl_senha.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha.setText("informações aqui");
        jPanel1.add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 297, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorBuscarCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorBuscarCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorBuscarCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorBuscarCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModeradorBuscarCL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nomeDeUsuario;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_telefone;
    // End of variables declaration//GEN-END:variables
}
