/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastro_e_Login;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

public class TelaModeradorMenuCL extends javax.swing.JFrame {

    TelaUsuarioLoginCL volta;
    UsuarioBancoCL banco;
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel tableModel;

    public TelaModeradorMenuCL() {
        initComponents();
    }

    public void setTableModel(DefaultTableModel tableModel) {
        this.tableModel = tableModel;
    }

    public void MostrarUsuarios() {
        for (int i = 0; i < banco.bancoDados.length; i++) {
            if (banco.bancoDados[i] != null) {
                setTableModel((DefaultTableModel) tbl_usuarios.getModel());

                Object[] rowData = {
                    banco.bancoDados[i].getID(),
                    banco.bancoDados[i].getNome(),
                    banco.bancoDados[i].getCpf(),
                    banco.bancoDados[i].getEmail(),
                    banco.bancoDados[i].getTelefone(),
                    banco.bancoDados[i].getNomeDeUsuario(),
                    banco.bancoDados[i].getSenha(),};
                tableModel.addRow(rowData);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        btn_cadastrar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Email", "Telefone", "Usuario", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tbl_usuarios);

        btn_cadastrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_alterar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_remover.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        jMenu1.setText("...");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_cadastrar)
                .addGap(45, 45, 45)
                .addComponent(btn_buscar)
                .addGap(45, 45, 45)
                .addComponent(btn_alterar)
                .addGap(46, 46, 46)
                .addComponent(btn_remover)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_buscar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_remover))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane,
                "Deseja retornar?", "Menu",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            volta.setVisible(true);
            volta.btnLimpar.doClick();
            setVisible(false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            String resposta = JOptionPane.showInputDialog(null, "Digite o ID do usuário que você deseja visualizar");
            if (resposta != null) {
                TelaModeradorBuscarCL novatela = new TelaModeradorBuscarCL();

                novatela.banco = this.banco;
                novatela.volta = this;

                novatela.setID(Integer.parseInt(resposta));
                novatela.mostrarPerfil();
                novatela.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuario não identificado!");
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        TelaModeradorCadastroCL novatela = new TelaModeradorCadastroCL();

        novatela.banco = this.banco;
        novatela.volta = this;
        novatela.setVisible(true);

    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        String resposta = JOptionPane.showInputDialog(null, "Digite o ID do usuário que você deseja remover");
        if (resposta != null) {
            for (int i = 0; i < banco.bancoDados.length; i++) {
                if (banco.bancoDados[i] != null) {
                    if (banco.bancoDados[i].getID() == Integer.parseInt(resposta)) {
                        banco.bancoDados[i] = null;
                        tableModel = (DefaultTableModel) tbl_usuarios.getModel();
                        tableModel.setRowCount(0);
                        MostrarUsuarios();
                        break;
                    }
                } else if (i == banco.bancoDados.length - 1) {
                    JOptionPane.showMessageDialog(null, "ID de usuário não encontrado");
                }
            }
        }

    }//GEN-LAST:event_btn_removerActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        try {

            String resposta = JOptionPane.showInputDialog(null, "Digite o ID do usuário que você deseja fazer alterações");
            if (resposta != null) {
                TelaModeradorAlterarCL novatela = new TelaModeradorAlterarCL();

                novatela.banco = banco;
                novatela.volta = this;

                novatela.setID(Integer.parseInt(resposta));
                novatela.preencherCampos();
                novatela.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuário não identificado! ");
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorMenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorMenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorMenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModeradorMenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModeradorMenuCL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
