/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Deposito_e_Saque;

import Cadastro_e_Login.TelaUsuarioLoginCL;
import Cadastro_e_Login.UsuarioBancoCL;
import MenuUsuario.TelaInicialMU;
import java.util.HashSet;
import javax.swing.JOptionPane;

public class TelaDS extends javax.swing.JFrame {

    TelaInicialMU telaLoby;
    UsuarioBancoCL banco;
    int ID;
    MetodosDS comandoDS = new MetodosDS();

    public void setTelaLoby(TelaInicialMU telaLoby) {
        this.telaLoby = telaLoby;
    }

    public void setBanco(UsuarioBancoCL banco) {
        this.banco = banco;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }
    
    
    
    

    public TelaDS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbtnDeposito = new javax.swing.JToggleButton();
        tbtnSaque = new javax.swing.JToggleButton();
        txt_senhaSD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_valorSD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saldoDS = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 405));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Saldo: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 60, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Saque/Depósito");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, -1));

        tbtnDeposito.setText("Deposito");
        tbtnDeposito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        tbtnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDepositoActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, 30));

        tbtnSaque.setText("Saque");
        tbtnSaque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        tbtnSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSaqueActionPerformed(evt);
            }
        });
        jPanel1.add(tbtnSaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 30));

        txt_senhaSD.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(255, 102, 0)));
        txt_senhaSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaSDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_senhaSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirme sua senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 130, 30));

        txt_valorSD.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(255, 102, 0)));
        txt_valorSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valorSDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_valorSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o valor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 120, 30));

        saldoDS.setForeground(new java.awt.Color(255, 255, 255));
        saldoDS.setText("jLabel5");
        jPanel1.add(saldoDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 6, 60, 30));

        jButton2.setText("Cancelar Deposito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDepositoActionPerformed

        if (tbtnSaque.isSelected()) {
            tbtnSaque.setSelected(false);
            tbtnDeposito.setSelected(true);
        }

    }//GEN-LAST:event_tbtnDepositoActionPerformed

    private void tbtnSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSaqueActionPerformed
        if (tbtnDeposito.isSelected()) {
            tbtnSaque.setSelected(true);
            tbtnDeposito.setSelected(false);
        }
    }//GEN-LAST:event_tbtnSaqueActionPerformed

    private void txt_valorSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valorSDActionPerformed

    }//GEN-LAST:event_txt_valorSDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        comandoDS.depositarOuSacar(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_senhaSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaSDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        telaLoby.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel saldoDS;
    public javax.swing.JToggleButton tbtnDeposito;
    public javax.swing.JToggleButton tbtnSaque;
    public javax.swing.JTextField txt_senhaSD;
    public javax.swing.JTextField txt_valorSD;
    // End of variables declaration//GEN-END:variables
}
