/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuUsuario;

import Cadastro_e_Login.TelaUsuarioLoginCL;
import Cadastro_e_Login.UsuarioBancoCL;

/**
 *
 * @author profslpa
 */
public class TelaPerfilMU extends javax.swing.JFrame {
    
    TelaUsuarioLoginCL login;
    UsuarioBancoCL banco;
    String senha;
    int ID;
    String pass = "";

    public void setID(int ID) {
        this.ID = ID;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    
    public TelaPerfilMU() {
        initComponents();
        
    }
    
    public void esconderSenha() {
        int comprimento = banco.bancoDados[ID - 1].getSenha().length();
        int i = 0;
        while (i < comprimento) {
            pass += "*";
            i++;
        }
    }
    
    public void mostrarPerfil() {
        lbl_id.setText("ID: " + ID);
        lbl_saldo.setText(String.valueOf("Saldo: " + banco.bancoDados[ID - 1].getSaldo()));
        lbl_nome.setText("Nome: " + banco.bancoDados[ID - 1].getNome());
        lbl_cpf.setText("CPF: " + banco.bancoDados[ID - 1].getCpf());
        lbl_email.setText("E-mail: " + banco.bancoDados[ID - 1].getEmail());
        lbl_telefone.setText("Telefone: " + banco.bancoDados[ID - 1].getTelefone());
        lbl_nomeDeUsuario.setText("Nome de usuário: " + banco.bancoDados[ID - 1].getNomeDeUsuario());
        senha = banco.bancoDados[ID - 1].getSenha();
        esconderSenha();
        lbl_senha.setText("Senha: " + pass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        tbtn_senha = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        lbl_saldo = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        lbl_nomeDeUsuario = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Alterar dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 120, 30));

        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID: ");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, -1));

        tbtn_senha.setText("Mostrar senha");
        tbtn_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_senhaActionPerformed(evt);
            }
        });
        jPanel1.add(tbtn_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_saldo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_saldo.setText("saldo aqui");
        jPanel1.add(lbl_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, 20));

        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setText("informações aqui");
        jPanel1.add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 280, 20));

        lbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cpf.setText("informações aqui");
        jPanel1.add(lbl_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 280, 20));

        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("informações aqui");
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 280, 20));

        lbl_telefone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefone.setText("informações aqui");
        jPanel1.add(lbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 280, 20));

        lbl_nomeDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nomeDeUsuario.setText("informações aqui");
        jPanel1.add(lbl_nomeDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 238, 20));

        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("informações aqui");
        jPanel1.add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 297, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/WhatsApp Image 2023-06-05 at 13.25.54_1.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbtn_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_senhaActionPerformed
        if (tbtn_senha.isSelected()) {lbl_senha.setText("Senha: " + senha); tbtn_senha.setText("Esconder senha");}
        else {lbl_senha.setText("Senha: " + pass); tbtn_senha.setText("Mostrar senha");}
    }//GEN-LAST:event_tbtn_senhaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaAlterarMU novatela = new TelaAlterarMU();
        novatela.banco = this.banco;
        novatela.login = this.login;
        novatela.telaperf = this;
        novatela.ID = this.ID;
        novatela.setarTXT();
        novatela.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfilMU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nomeDeUsuario;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JToggleButton tbtn_senha;
    // End of variables declaration//GEN-END:variables
}
