/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuUsuario;

import CacaNiquel.TelaCN;
import Cadastro_e_Login.UsuarioHistoricoCL;
import Cadastro_e_Login.TelaUsuarioLoginCL;
import Cadastro_e_Login.UsuarioBancoCL;
import Deposito_e_Saque.TelaDS;
import BlackJack.TelaBJ;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class TelaInicialMU extends javax.swing.JFrame {

    public TelaUsuarioLoginCL login;
    int ID;
    String senha;
    TelaHistoricoMU historico = new TelaHistoricoMU();
    UsuarioBancoCL banco;
    double saldoCacaNiquel;

    public void setSaldoCacaNiquel(double saldoCacaNiquel) {
        this.saldoCacaNiquel = saldoCacaNiquel;
    }
    
    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public void setLogin(TelaUsuarioLoginCL login) {
        this.login = login;
    }

    public void setBanco(UsuarioBancoCL banco) {
        this.banco = banco;
    }
    

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getID() {
        return ID;
    }

    

       
    public TelaInicialMU() {
        initComponents();
        setTitle("Tela de Início");
        historico.setTelaLoby(this);
    }
    
    public void mostrarHistorico() {
        for (int i = 0; i < banco.historico.length; i++) {
            if (this.banco.historico[ID - 1] != null && i == (ID - 1)) {
                for (int j = 0; j < this.banco.historico[i].length; j++) {
                    if (this.banco.historico[i][j] != null) {
                    historico.setTableModel((DefaultTableModel) historico.tabelaHistorico.getModel());
                    Object[] rowData = {banco.historico[ID - 1][j].getID_aposta(), banco.historico[ID - 1][j].getJogo(),banco.historico[ID - 1][j].getLP()};
                    historico.tableModel.addRow(rowData);
                    historico.apagarHist.setEnabled(true);
                    }
                }
              }
            }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPerfil = new javax.swing.JButton();
        btn_historico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_usuarioLog = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        btn_depositar_sacar = new javax.swing.JButton();
        voltarTelaLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_blackjack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_roleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        btn_historico.setText("Histórico de Jogos");
        btn_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("R$");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 40));

        lbl_usuarioLog.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_usuarioLog.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuarioLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_usuarioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 30));

        lbl_saldo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_saldo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_saldo.setText("1");
        getContentPane().add(lbl_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, 20));

        btn_depositar_sacar.setText("Sacar / Depositar");
        btn_depositar_sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositar_sacarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_depositar_sacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, -1));

        voltarTelaLogin.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        voltarTelaLogin.setText("Voltar");
        voltarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(voltarTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Escolha um modo de jogo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        btn_blackjack.setBackground(new java.awt.Color(255, 0, 153));
        btn_blackjack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_blackjack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/baralho1.jpg"))); // NOI18N
        btn_blackjack.setText("Black Jack");
        btn_blackjack.setToolTipText("");
        btn_blackjack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blackjackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_blackjack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Caça níquel");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Black  Jack");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, -1));

        btn_roleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/roleta2.jpg"))); // NOI18N
        btn_roleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roletaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_roleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WhatsApp_Image_2023-06-05_at_13.25.54.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_blackjackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blackjackActionPerformed
        TelaBJ novatela = new TelaBJ();
        novatela.hist = historico;
        novatela.inin = this;
        novatela.setID(this.ID);
        novatela.setBanco(this.banco);
        novatela.setSaldo(Double.parseDouble(lbl_saldo.getText()));
        novatela.setVisible(true);
        novatela.Apostar();
    }//GEN-LAST:event_btn_blackjackActionPerformed

    private void voltarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaLoginActionPerformed
        login.setVisible(true);
        login.btnLimpar.doClick();
        dispose();
    }//GEN-LAST:event_voltarTelaLoginActionPerformed

    private void btn_depositar_sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositar_sacarActionPerformed
        TelaDS novatela = new TelaDS();
        
        novatela.setTelaLoby(this);
        novatela.setBanco(this.banco);
        novatela.setID(this.ID);
        novatela.setVisible(true);
        setVisible(false);
        novatela.saldoDS.setText(lbl_saldo.getText());
        
    }//GEN-LAST:event_btn_depositar_sacarActionPerformed

    private void btn_roletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roletaActionPerformed
        TelaCN novatela = new TelaCN();
        novatela.setID(ID);
        novatela.setBanco(this.banco);
        novatela.setHistorico(historico);
        novatela.setSaldo(saldoCacaNiquel);
        novatela.premio.setText(String.valueOf(login.getPremioCacaNiquel()));
        novatela.setSaldo(banco.bancoDados[ID - 1].getSaldoCacaNiquel());
        novatela.mostrarSaldo();
        novatela.setInin(this);
        novatela.setVisible(true);
    }//GEN-LAST:event_btn_roletaActionPerformed

    private void btn_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historicoActionPerformed
        historico.setVisible(true);
        historico.setBanco(this.banco);
        historico.setHist(this.banco.historico);
    }//GEN-LAST:event_btn_historicoActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
       TelaPerfilMU novaTela = new TelaPerfilMU();
       novaTela.banco = banco;
       novaTela.login = this.login;
       novaTela.ID = this.ID;
       novaTela.mostrarPerfil();
       
       novaTela.setVisible(true);
       
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialMU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialMU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerfil;
    public javax.swing.JButton btn_blackjack;
    private javax.swing.JButton btn_depositar_sacar;
    private javax.swing.JButton btn_historico;
    public javax.swing.JButton btn_roleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel lbl_saldo;
    public javax.swing.JLabel lbl_usuarioLog;
    private javax.swing.JButton voltarTelaLogin;
    // End of variables declaration//GEN-END:variables
}
