/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BlackJack;

/**
 *
 * @author Vinícius
 */
import MenuUsuario.TelaHistoricoMU;
import Cadastro_e_Login.UsuarioBancoCL;
import MenuUsuario.MetodosHistoricoMU;
import MenuUsuario.TelaInicialMU;
import java.util.Random;
import java.util.Arrays;

public class TelaBJ extends javax.swing.JFrame {
    Random e = new Random();
    
    int i = 0;
    int aleatorio = 0;
    int pontosOp;
    double saldo;
    double apostas;
    double saldoInicial;
    UsuarioBancoCL banco;
    int ID;
    
    String[] cartas = new String[52];
    int[] valoresCartas = new int[52];
    
    public TelaHistoricoMU hist;
    MetodosHistoricoMU comando = new MetodosHistoricoMU();
    public TelaInicialMU inin;
    
    ComandoVinteumBJ comandovinteum = new ComandoVinteumBJ();
    MetodosCartasBJ comandocartas = new MetodosCartasBJ();
    ResultadosBJ Resultados = new ResultadosBJ();
    TelaApostaBJ telaaposta = new TelaApostaBJ();
    
    public void setID(int ID) {
        this.ID = ID;
    }

    public int getID() {
        return ID;
    }
    
    public void setBanco(UsuarioBancoCL banco) {
        this.banco = banco;
    }
    
    public double getApostas() {
        return this.apostas;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public double getSaldoInicial() {
        return saldoInicial;
    }
    
    
    
    public TelaBJ() {
        initComponents();
        
        this.pontosOp = comandovinteum.pontosOponente;
        
        comandocartas.esconderCartas(this);

        comandovinteum.prepararBaralho(cartas, valoresCartas);
        
        jogarNovamente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p9 = new javax.swing.JPanel();
        cart9 = new javax.swing.JLabel();
        p10 = new javax.swing.JPanel();
        cart10 = new javax.swing.JLabel();
        p8 = new javax.swing.JPanel();
        cart8 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        cart7 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        cart5 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        cart6 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        cart3 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        cart2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        cart1 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        cart4 = new javax.swing.JLabel();
        p11 = new javax.swing.JPanel();
        cart11 = new javax.swing.JLabel();
        botaoJogar = new javax.swing.JButton();
        p13 = new javax.swing.JPanel();
        cart13 = new javax.swing.JLabel();
        verso13 = new javax.swing.JLabel();
        p28 = new javax.swing.JPanel();
        cart28 = new javax.swing.JLabel();
        verso28 = new javax.swing.JLabel();
        p29 = new javax.swing.JPanel();
        cart29 = new javax.swing.JLabel();
        verso29 = new javax.swing.JLabel();
        p30 = new javax.swing.JPanel();
        cart30 = new javax.swing.JLabel();
        verso30 = new javax.swing.JLabel();
        p31 = new javax.swing.JPanel();
        cart31 = new javax.swing.JLabel();
        verso31 = new javax.swing.JLabel();
        p32 = new javax.swing.JPanel();
        cart32 = new javax.swing.JLabel();
        verso32 = new javax.swing.JLabel();
        p33 = new javax.swing.JPanel();
        cart33 = new javax.swing.JLabel();
        verso33 = new javax.swing.JLabel();
        p34 = new javax.swing.JPanel();
        cart34 = new javax.swing.JLabel();
        verso34 = new javax.swing.JLabel();
        p35 = new javax.swing.JPanel();
        cart35 = new javax.swing.JLabel();
        verso35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        voltarMenu = new javax.swing.JButton();
        botaoParar = new javax.swing.JButton();
        apostaUsu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p36 = new javax.swing.JPanel();
        cart36 = new javax.swing.JLabel();
        verso36 = new javax.swing.JLabel();
        p12 = new javax.swing.JPanel();
        cart12 = new javax.swing.JLabel();
        verso12 = new javax.swing.JLabel();
        jogarNovamente = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        pontuacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p9.setBackground(new java.awt.Color(255, 255, 255));
        p9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart9.setBackground(new java.awt.Color(255, 204, 204));
        cart9.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart9.setText("jLabel1");

        javax.swing.GroupLayout p9Layout = new javax.swing.GroupLayout(p9);
        p9.setLayout(p9Layout);
        p9Layout.setHorizontalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p9Layout.setVerticalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p9Layout.createSequentialGroup()
                .addComponent(cart9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 425, -1, -1));

        p10.setBackground(new java.awt.Color(255, 255, 255));
        p10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart10.setBackground(new java.awt.Color(255, 204, 204));
        cart10.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart10.setText("jLabel1");

        javax.swing.GroupLayout p10Layout = new javax.swing.GroupLayout(p10);
        p10.setLayout(p10Layout);
        p10Layout.setHorizontalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p10Layout.setVerticalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p10Layout.createSequentialGroup()
                .addComponent(cart10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 323, -1, 96));

        p8.setBackground(new java.awt.Color(255, 255, 255));
        p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart8.setBackground(new java.awt.Color(255, 204, 204));
        cart8.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart8.setText("jLabel1");

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addComponent(cart8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 425, -1, -1));

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart7.setBackground(new java.awt.Color(255, 204, 204));
        cart7.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart7.setText("jLabel1");

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addComponent(cart7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 425, -1, -1));

        p5.setBackground(new java.awt.Color(255, 255, 255));
        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart5.setBackground(new java.awt.Color(255, 204, 204));
        cart5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart5.setText("jLabel1");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addComponent(cart5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 425, -1, -1));

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart6.setBackground(new java.awt.Color(255, 204, 204));
        cart6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart6.setText("jLabel1");

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addComponent(cart6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 425, -1, -1));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart3.setBackground(new java.awt.Color(255, 204, 204));
        cart3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart3.setText("jLabel1");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addComponent(cart3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 425, -1, -1));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart2.setBackground(new java.awt.Color(255, 204, 204));
        cart2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart2.setText("jLabel1");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(cart2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 425, -1, -1));

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cart1.setBackground(new java.awt.Color(255, 204, 204));
        cart1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart1.setText("jLabel1");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 425, -1, -1));

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart4.setBackground(new java.awt.Color(255, 204, 204));
        cart4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart4.setText("jLabel1");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addComponent(cart4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 425, -1, -1));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart11.setBackground(new java.awt.Color(255, 204, 204));
        cart11.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart11.setText("jLabel1");

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cart11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addComponent(cart11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        getContentPane().add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 323, -1, -1));

        botaoJogar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoJogar.setText("Tirar carta");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 110, 40));

        p13.setBackground(new java.awt.Color(255, 255, 255));
        p13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart13.setBackground(new java.awt.Color(255, 204, 204));
        cart13.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart13.setText("jLabel1");
        p13.add(cart13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p13.add(verso13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 58, 67, 92));

        p28.setBackground(new java.awt.Color(255, 255, 255));
        p28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart28.setBackground(new java.awt.Color(255, 204, 204));
        cart28.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart28.setText("jLabel1");
        p28.add(cart28, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p28.add(verso28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 58, 67, 92));

        p29.setBackground(new java.awt.Color(255, 255, 255));
        p29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart29.setBackground(new java.awt.Color(255, 204, 204));
        cart29.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart29.setText("jLabel1");
        p29.add(cart29, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p29.add(verso29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 58, 67, 92));

        p30.setBackground(new java.awt.Color(255, 255, 255));
        p30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart30.setBackground(new java.awt.Color(255, 204, 204));
        cart30.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart30.setText("jLabel1");
        p30.add(cart30, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p30.add(verso30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 58, 67, 92));

        p31.setBackground(new java.awt.Color(255, 255, 255));
        p31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart31.setBackground(new java.awt.Color(255, 204, 204));
        cart31.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart31.setText("jLabel1");
        p31.add(cart31, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p31.add(verso31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 58, 67, 92));

        p32.setBackground(new java.awt.Color(255, 255, 255));
        p32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart32.setBackground(new java.awt.Color(255, 204, 204));
        cart32.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart32.setText("jLabel1");
        p32.add(cart32, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p32.add(verso32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 58, 67, 92));

        p33.setBackground(new java.awt.Color(255, 255, 255));
        p33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart33.setBackground(new java.awt.Color(255, 204, 204));
        cart33.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart33.setText("jLabel1");
        p33.add(cart33, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p33.add(verso33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 58, 67, 92));

        p34.setBackground(new java.awt.Color(255, 255, 255));
        p34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart34.setBackground(new java.awt.Color(255, 204, 204));
        cart34.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart34.setText("jLabel1");
        p34.add(cart34, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p34.add(verso34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 58, 67, 92));

        p35.setBackground(new java.awt.Color(255, 255, 255));
        p35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart35.setBackground(new java.awt.Color(255, 204, 204));
        cart35.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart35.setText("jLabel1");
        p35.add(cart35, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p35.add(verso35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p35, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 67, 92));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oponente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 149, -1));

        voltarMenu.setText("Voltar ao menu");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(voltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, 32));

        botaoParar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoParar.setText("Parar");
        botaoParar.setAutoscrolls(true);
        botaoParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPararActionPerformed(evt);
            }
        });
        getContentPane().add(botaoParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, 35));

        apostaUsu.setForeground(new java.awt.Color(255, 255, 255));
        apostaUsu.setText("0");
        getContentPane().add(apostaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 70, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aposta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 47, 30));

        p36.setBackground(new java.awt.Color(255, 255, 255));
        p36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart36.setBackground(new java.awt.Color(255, 204, 204));
        cart36.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart36.setText("jLabel1");
        p36.add(cart36, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p36.add(verso36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p36, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 156, 67, 92));

        p12.setBackground(new java.awt.Color(255, 255, 255));
        p12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        p12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart12.setBackground(new java.awt.Color(255, 204, 204));
        cart12.setFont(new java.awt.Font("Imprint MT Shadow", 0, 32)); // NOI18N
        cart12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cart12.setText("jLabel1");
        p12.add(cart12, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 44, 59));

        verso12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto_verso_carta.png"))); // NOI18N
        verso12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        p12.add(verso12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 92));

        getContentPane().add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 67, 92));

        jogarNovamente.setText("Jogar novamente");
        jogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jogarNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 140, 30));

        resultado.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 80, 30));

        pontuacao.setForeground(new java.awt.Color(255, 255, 255));
        pontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 66, 28));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pontuação");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBlackJack.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 720, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
        this.i++;
        aleatorio = e.nextInt(0,101);
        
        if (pontosOp < 11) {
            pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 13 && aleatorio <= 95) {
            pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 15 && aleatorio <= 80) {
            pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 17 && aleatorio <= 40) {
            pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 20 && aleatorio <= 10) {
            pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else {}
        
        comandovinteum.puxarCartas(cartas, valoresCartas, i, this);
    }//GEN-LAST:event_botaoJogarActionPerformed

    private void botaoPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPararActionPerformed
       this.saldoInicial = apostas;
       botaoJogar.setEnabled(false);
       botaoParar.setEnabled(false);
       jogarNovamente.setEnabled(false);
       Boolean parar = true;
       
       
       while (parar) {
       aleatorio = e.nextInt(0,101);
        if (pontosOp < 11) {
            this.i++;pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 13 && aleatorio <= 95) {
            this.i++;pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 15 && aleatorio <= 80) {
            this.i++;pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 17 && aleatorio <= 40) {
            this.i++;pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else if(pontosOp < 20 && aleatorio <= 10) {
            this.i++;pontosOp += comandovinteum.puxarCartasOp(cartas, valoresCartas, i, this);
        }
        else {parar = false;}
        }
        comandocartas.mostrarCartas(this);
        
        Resultados.mostrarResultado(comandovinteum.pontosUsuario, this.pontosOp, this);
        
        comando.inserirHistBlackJack(this, banco, hist);
        banco.bancoDados[inin.getID() - 1].setSaldo(saldo + (apostas - saldoInicial));
        inin.lbl_saldo.setText(String.valueOf(saldo + (apostas - saldoInicial)));
        jogarNovamente.setEnabled(true);
    }//GEN-LAST:event_botaoPararActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        dispose(); 
        inin.setVisible(true);
    }//GEN-LAST:event_voltarMenuActionPerformed

    public void Apostar() {
        setVisible(false);
        TelaApostaBJ novatela = new TelaApostaBJ();
        novatela.aposta.setText(String.valueOf((double)saldo));
        novatela.telainicial = this;
        novatela.inin = inin;
        novatela.setVisible(true);
    }
    
    private void jogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNovamenteActionPerformed
        voltarMenu.doClick();
        inin.btn_blackjack.doClick();
    }//GEN-LAST:event_jogarNovamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel apostaUsu;
    public javax.swing.JButton botaoJogar;
    public javax.swing.JButton botaoParar;
    public javax.swing.JLabel cart1;
    public javax.swing.JLabel cart10;
    public javax.swing.JLabel cart11;
    public javax.swing.JLabel cart12;
    public javax.swing.JLabel cart13;
    public javax.swing.JLabel cart2;
    public javax.swing.JLabel cart28;
    public javax.swing.JLabel cart29;
    public javax.swing.JLabel cart3;
    public javax.swing.JLabel cart30;
    public javax.swing.JLabel cart31;
    public javax.swing.JLabel cart32;
    public javax.swing.JLabel cart33;
    public javax.swing.JLabel cart34;
    public javax.swing.JLabel cart35;
    public javax.swing.JLabel cart36;
    public javax.swing.JLabel cart4;
    public javax.swing.JLabel cart5;
    public javax.swing.JLabel cart6;
    public javax.swing.JLabel cart7;
    public javax.swing.JLabel cart8;
    public javax.swing.JLabel cart9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton jogarNovamente;
    public javax.swing.JPanel p1;
    public javax.swing.JPanel p10;
    public javax.swing.JPanel p11;
    public javax.swing.JPanel p12;
    public javax.swing.JPanel p13;
    public javax.swing.JPanel p2;
    public javax.swing.JPanel p28;
    public javax.swing.JPanel p29;
    public javax.swing.JPanel p3;
    public javax.swing.JPanel p30;
    public javax.swing.JPanel p31;
    public javax.swing.JPanel p32;
    public javax.swing.JPanel p33;
    public javax.swing.JPanel p34;
    public javax.swing.JPanel p35;
    public javax.swing.JPanel p36;
    public javax.swing.JPanel p4;
    public javax.swing.JPanel p5;
    public javax.swing.JPanel p6;
    public javax.swing.JPanel p7;
    public javax.swing.JPanel p8;
    public javax.swing.JPanel p9;
    public javax.swing.JLabel pontuacao;
    public javax.swing.JLabel resultado;
    public javax.swing.JLabel verso12;
    public javax.swing.JLabel verso13;
    public javax.swing.JLabel verso28;
    public javax.swing.JLabel verso29;
    public javax.swing.JLabel verso30;
    public javax.swing.JLabel verso31;
    public javax.swing.JLabel verso32;
    public javax.swing.JLabel verso33;
    public javax.swing.JLabel verso34;
    public javax.swing.JLabel verso35;
    public javax.swing.JLabel verso36;
    public javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables
}
